### ISSUE TITLE
Unexpected display when selecting a method.

### ISSUE THREAD

**Issue by deepanshs** [deepanshs/mrsimulator-app#19]
Steps to reproduce. 

1) Open the example, wollastonite.
2) Add a new method (isotope 29Si).
3) Goto the **Features** tab.
4) Run least-squares minimization. (This will raise an error as expected: *LeastSquaresAnalysisError: Please attach measurement(s) for method(s) at index(es) [1] before performing the least-squares analysis.*) 
5) Next, Goto the **Methods** tab and click on the unselected method. 

Expected behavior: The screen should show the method parameters of the selected method.

What is observed: The screen jumps to the **Features** tab. This should not happen.

**Comment by mgiammar** [comment]
Issues is resolved in #21
